-- Expand supported profile roles to include manager + unverified (keep legacy 'client')
-- NOTE: 010_add_role_to_profiles.sql introduced the role column + initial check constraint.

-- Drop the previous check constraint (name is the default generated by Postgres)
ALTER TABLE profiles
DROP CONSTRAINT IF EXISTS profiles_role_check;

-- Re-add with the expanded set.
ALTER TABLE profiles
ADD CONSTRAINT profiles_role_check
CHECK (role IN ('admin', 'manager', 'client', 'user', 'unverified'));

-- Optional: keep existing data as-is (some environments use 'client' for managers).
-- If you want to migrate legacy 'client' → 'manager', uncomment:
-- UPDATE profiles SET role = 'manager' WHERE role = 'client';

